export default {
  roles: state => state.user.roles,
  isAdmin: state => state.user.isAdmin,
  permissions: state => state.user.permissions,
  avatar: state => state.user.avatar,
  device: state => state.app.device,
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  loading: state => state.app.loading,
  previewImg: state => state.app.previewImg,
  previewImgList: state => state.app.previewImgList,
  theme: state => state.settings.theme,
  warning: state => state.settings.warning,
  success: state => state.settings.success,
  danger: state => state.settings.danger,
  sidebarLogo: state => state.settings.sidebarLogo,
  sidebarName: state => state.settings.sidebarName,
  tagsView: state => state.settings.tagsView,
  showSettings: state => state.settings.showSettings,
  fixedHeader: state => state.settings.fixedHeader,
  routes: state => state.routes.routes,
  addRoutes: state => state.routes.addRoutes,
  btnPrems: state => state.routes.btnPrems,
  isInject: state => state.routes.isInject,
  visitedViews: state => state.views.visitedViews,
  cachedViews: state => state.views.cachedViews
}